-- DÉSACTIVÉ : Les comptes démo ne doivent pas être créés en production
-- =================================================================
-- MIGRATION 004: Demo Accounts Initialization (ARCHIVED)
-- Version: 1.1 (Updated with environment warnings)
-- Description: Creates setup_demo_accounts() function for initializing
--              demo/test user accounts with sample data
--
-- ⚠️  WARNING: DEVELOPMENT/STAGING ENVIRONMENTS ONLY
-- =================================================================
-- This migration creates demo accounts that should NEVER be used in
-- production environments. The setup_demo_accounts() function should
-- ONLY be called in development or staging environments.
--
-- Environment enforcement is handled at the application layer via
-- the ENABLE_DEMO_ACCOUNTS environment variable (see .env.example).
--
-- DO NOT manually call setup_demo_accounts() in production databases!
-- =================================================================

-- Cette fonction configure les comptes après leur création dans Supabase Auth
-- ⚠️  DEV/STAGING ONLY: This function should only be executed in non-production environments
-- CREATE OR REPLACE FUNCTION setup_demo_accounts()
-- RETURNS void AS $$
-- DECLARE
--     v_admin_id UUID;
--     v_student_id UUID;
--     v_demo_id UUID;
-- BEGIN
--     -- Récupérer les IDs des utilisateurs
--     SELECT id INTO v_admin_id FROM auth.users WHERE email = 'admin@geniawebtraining.com';
--     SELECT id INTO v_student_id FROM auth.users WHERE email = 'student@geniawebtraining.com';
--     SELECT id INTO v_demo_id FROM auth.users WHERE email = 'demo@geniawebtraining.com';
--
--     -- Si les comptes n'existent pas, afficher un message
--     IF v_admin_id IS NULL OR v_student_id IS NULL OR v_demo_id IS NULL THEN
--         RAISE NOTICE 'Créez d''abord les comptes dans Supabase Auth avec ces emails:';
--         RAISE NOTICE '- admin@example.com (Password: [MOT_DE_PASSE_SUPPRIME])';
--         RAISE NOTICE '- student@example.com (Password: [MOT_DE_PASSE_SUPPRIME])';
--         RAISE NOTICE '- demo@example.com (Password: [MOT_DE_PASSE_SUPPRIME])';
--         RETURN;
--     END IF;
--
--     -- Configurer le compte admin
--     IF v_admin_id IS NOT NULL THEN
--         -- Mettre à jour le rôle dans user_profiles
--         UPDATE user_profiles
--         SET
--             role = 'admin',
--             display_name = 'Administrateur GENIA',
--             bio = 'Administrateur de la plateforme GENIA Web Training',
--             onboarding_completed = true,
--             updated_at = NOW()
--         WHERE user_id = v_admin_id;
--
--         -- Mettre à jour les points
--         UPDATE user_points
--         SET
--             total_points = 1000,
--             level = 10,
--             updated_at = NOW()
--         WHERE user_id = v_admin_id;
--
--         -- Initialiser la progression GENIA
--         INSERT INTO user_progress_genia (
--             user_id,
--             current_level,
--             total_messages,
--             exercises_completed,
--             exercises_succeeded,
--             average_score
--         )
--         VALUES (v_admin_id, 'advanced', 100, 50, 45, 90.0)
--         ON CONFLICT (user_id) DO UPDATE
--         SET
--             current_level = EXCLUDED.current_level,
--             total_messages = EXCLUDED.total_messages,
--             exercises_completed = EXCLUDED.exercises_completed,
--             exercises_succeeded = EXCLUDED.exercises_succeeded,
--             average_score = EXCLUDED.average_score,
--             updated_at = NOW();
--
--         RAISE NOTICE 'Compte admin configuré: %', v_admin_id;
--     END IF;
--
--     -- Configurer le compte étudiant test
--     IF v_student_id IS NOT NULL THEN
--         UPDATE user_profiles
--         SET
--             display_name = 'Étudiant Test',
--             bio = 'Compte test pour les étudiants',
--             onboarding_completed = false,
--             updated_at = NOW()
--         WHERE user_id = v_student_id;
--
--         -- Initialiser la progression GENIA
--         INSERT INTO user_progress_genia (user_id)
--         VALUES (v_student_id)
--         ON CONFLICT (user_id) DO NOTHING;
--
--         RAISE NOTICE 'Compte étudiant configuré: %', v_student_id;
--     END IF;
--
--     -- Configurer le compte démo avec des données
--     IF v_demo_id IS NOT NULL THEN
--         UPDATE user_profiles
--         SET
--             display_name = 'Compte Démo',
--             bio = 'Compte de démonstration avec données exemples',
--             onboarding_completed = true,
--             updated_at = NOW()
--         WHERE user_id = v_demo_id;
--
--         UPDATE user_points
--         SET
--             total_points = 250,
--             level = 3,
--             streak_days = 7,
--             updated_at = NOW()
--         WHERE user_id = v_demo_id;
--
--         INSERT INTO user_progress_genia (
--             user_id,
--             current_level,
--             total_messages,
--             exercises_completed,
--             exercises_succeeded,
--             average_score,
--             streak_days
--         )
--         VALUES (v_demo_id, 'intermediate', 25, 10, 8, 80.0, 7)
--         ON CONFLICT (user_id) DO UPDATE
--         SET
--             current_level = EXCLUDED.current_level,
--             total_messages = EXCLUDED.total_messages,
--             exercises_completed = EXCLUDED.exercises_completed,
--             exercises_succeeded = EXCLUDED.exercises_succeeded,
--             average_score = EXCLUDED.average_score,
--             streak_days = EXCLUDED.streak_days,
--             updated_at = NOW();
--
--         RAISE NOTICE 'Compte démo configuré: %', v_demo_id;
--     END IF;
--
--     RAISE NOTICE 'Configuration terminée !';
-- END;
-- $$ LANGUAGE plpgsql;

-- =================================================================
-- ⚠️  CRITICAL: DO NOT EXECUTE IN PRODUCTION
-- =================================================================
-- This function should ONLY be called in development/staging environments.
--
-- To use this function:
-- 1. Ensure ENABLE_DEMO_ACCOUNTS=true in your .env file (dev/staging only)
-- 2. Create the demo accounts manually in Supabase Auth first
-- 3. Then call: SELECT setup_demo_accounts();
--
-- PRODUCTION SAFETY:
-- - Set ENABLE_DEMO_ACCOUNTS=false (or omit) in production .env
-- - Never manually call this function in production databases
-- - Demo accounts should not exist in production environments
-- =================================================================

-- Pour vérifier les comptes après configuration :
-- SELECT
--     au.email,
--     up.role,
--     up.display_name,
--     upg.current_level,
--     upo.total_points,
--     upo.level as user_level
-- FROM auth.users au
-- LEFT JOIN user_profiles up ON au.id = up.user_id
-- LEFT JOIN user_progress_genia upg ON au.id = upg.user_id
-- LEFT JOIN user_points upo ON au.id = upo.user_id
-- WHERE au.email IN (
--     'admin@example.com',
--     'student@example.com',
--     'demo@example.com'
-- );
